import { Chess } from '../src/chess'

describe('History', () => {
  const chess = new Chess()
  const tests = [
    {
      verbose: false,
      fen: '4q2k/2r1r3/4PR1p/p1p5/P1Bp1Q1P/1P6/6P1/6K1 b - - 4 41',
      moves: [
        'c4',
        'e6',
        'Nf3',
        'd5',
        'd4',
        'Nf6',
        'Nc3',
        'Be7',
        'Bg5',
        'O-O',
        'e3',
        'h6',
        'Bh4',
        'b6',
        'cxd5',
        'Nxd5',
        'Bxe7',
        'Qxe7',
        'Nxd5',
        'exd5',
        'Rc1',
        'Be6',
        'Qa4',
        'c5',
        'Qa3',
        'Rc8',
        'Bb5',
        'a6',
        'dxc5',
        'bxc5',
        'O-O',
        'Ra7',
        'Be2',
        'Nd7',
        'Nd4',
        'Qf8',
        'Nxe6',
        'fxe6',
        'e4',
        'd4',
        'f4',
        'Qe7',
        'e5',
        'Rb8',
        'Bc4',
        'Kh8',
        'Qh3',
        'Nf8',
        'b3',
        'a5',
        'f5',
        'exf5',
        'Rxf5',
        'Nh7',
        'Rcf1',
        'Qd8',
        'Qg3',
        'Re7',
        'h4',
        'Rbb7',
        'e6',
        'Rbc7',
        'Qe5',
        'Qe8',
        'a4',
        'Qd8',
        'R1f2',
        'Qe8',
        'R2f3',
        'Qd8',
        'Bd3',
        'Qe8',
        'Qe4',
        'Nf6',
        'Rxf6',
        'gxf6',
        'Rxf6',
        'Kg8',
        'Bc4',
        'Kh8',
        'Qf4',
      ],
    },
    {
      verbose: true,
      fen: '4q2k/2r1r3/4PR1p/p1p5/P1Bp1Q1P/1P6/6P1/6K1 b - - 4 41',
      moves: [
        {
          color: 'w',
          fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
          from: 'c2',
          to: 'c4',
          flags: 'b',
          piece: 'p',
          san: 'c4',
        },
        {
          color: 'b',
          fen: 'rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq c3 0 1',
          from: 'e7',
          to: 'e6',
          flags: 'n',
          piece: 'p',
          san: 'e6',
        },
        {
          color: 'w',
          fen: 'rnbqkbnr/pppp1ppp/4p3/8/2P5/8/PP1PPPPP/RNBQKBNR w KQkq - 0 2',
          from: 'g1',
          to: 'f3',
          flags: 'n',
          piece: 'n',
          san: 'Nf3',
        },
        {
          color: 'b',
          fen: 'rnbqkbnr/pppp1ppp/4p3/8/2P5/5N2/PP1PPPPP/RNBQKB1R b KQkq - 1 2',
          from: 'd7',
          to: 'd5',
          flags: 'b',
          piece: 'p',
          san: 'd5',
        },
        {
          color: 'w',
          fen: 'rnbqkbnr/ppp2ppp/4p3/3p4/2P5/5N2/PP1PPPPP/RNBQKB1R w KQkq d6 0 3',
          from: 'd2',
          to: 'd4',
          flags: 'b',
          piece: 'p',
          san: 'd4',
        },
        {
          color: 'b',
          fen: 'rnbqkbnr/ppp2ppp/4p3/3p4/2PP4/5N2/PP2PPPP/RNBQKB1R b KQkq d3 0 3',
          from: 'g8',
          to: 'f6',
          flags: 'n',
          piece: 'n',
          san: 'Nf6',
        },
        {
          color: 'w',
          fen: 'rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/5N2/PP2PPPP/RNBQKB1R w KQkq - 1 4',
          from: 'b1',
          to: 'c3',
          flags: 'n',
          piece: 'n',
          san: 'Nc3',
        },
        {
          color: 'b',
          fen: 'rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R b KQkq - 2 4',
          from: 'f8',
          to: 'e7',
          flags: 'n',
          piece: 'b',
          san: 'Be7',
        },
        {
          color: 'w',
          fen: 'rnbqk2r/ppp1bppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 3 5',
          from: 'c1',
          to: 'g5',
          flags: 'n',
          piece: 'b',
          san: 'Bg5',
        },
        {
          color: 'b',
          fen: 'rnbqk2r/ppp1bppp/4pn2/3p2B1/2PP4/2N2N2/PP2PPPP/R2QKB1R b KQkq - 4 5',
          from: 'e8',
          to: 'g8',
          flags: 'k',
          piece: 'k',
          san: 'O-O',
        },
        {
          color: 'w',
          fen: 'rnbq1rk1/ppp1bppp/4pn2/3p2B1/2PP4/2N2N2/PP2PPPP/R2QKB1R w KQ - 5 6',
          from: 'e2',
          to: 'e3',
          flags: 'n',
          piece: 'p',
          san: 'e3',
        },
        {
          color: 'b',
          fen: 'rnbq1rk1/ppp1bppp/4pn2/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 6',
          from: 'h7',
          to: 'h6',
          flags: 'n',
          piece: 'p',
          san: 'h6',
        },
        {
          color: 'w',
          fen: 'rnbq1rk1/ppp1bpp1/4pn1p/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 7',
          from: 'g5',
          to: 'h4',
          flags: 'n',
          piece: 'b',
          san: 'Bh4',
        },
        {
          color: 'b',
          fen: 'rnbq1rk1/ppp1bpp1/4pn1p/3p4/2PP3B/2N1PN2/PP3PPP/R2QKB1R b KQ - 1 7',
          from: 'b7',
          to: 'b6',
          flags: 'n',
          piece: 'p',
          san: 'b6',
        },
        {
          color: 'w',
          fen: 'rnbq1rk1/p1p1bpp1/1p2pn1p/3p4/2PP3B/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 8',
          from: 'c4',
          to: 'd5',
          flags: 'c',
          piece: 'p',
          san: 'cxd5',
          captured: 'p',
        },
        {
          color: 'b',
          fen: 'rnbq1rk1/p1p1bpp1/1p2pn1p/3P4/3P3B/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 8',
          from: 'f6',
          to: 'd5',
          flags: 'c',
          piece: 'n',
          san: 'Nxd5',
          captured: 'p',
        },
        {
          color: 'w',
          fen: 'rnbq1rk1/p1p1bpp1/1p2p2p/3n4/3P3B/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 9',
          from: 'h4',
          to: 'e7',
          flags: 'c',
          piece: 'b',
          san: 'Bxe7',
          captured: 'b',
        },
        {
          color: 'b',
          fen: 'rnbq1rk1/p1p1Bpp1/1p2p2p/3n4/3P4/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 9',
          from: 'd8',
          to: 'e7',
          flags: 'c',
          piece: 'q',
          san: 'Qxe7',
          captured: 'b',
        },
        {
          color: 'w',
          fen: 'rnb2rk1/p1p1qpp1/1p2p2p/3n4/3P4/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 10',
          from: 'c3',
          to: 'd5',
          flags: 'c',
          piece: 'n',
          san: 'Nxd5',
          captured: 'n',
        },
        {
          color: 'b',
          fen: 'rnb2rk1/p1p1qpp1/1p2p2p/3N4/3P4/4PN2/PP3PPP/R2QKB1R b KQ - 0 10',
          from: 'e6',
          to: 'd5',
          flags: 'c',
          piece: 'p',
          san: 'exd5',
          captured: 'n',
        },
        {
          color: 'w',
          fen: 'rnb2rk1/p1p1qpp1/1p5p/3p4/3P4/4PN2/PP3PPP/R2QKB1R w KQ - 0 11',
          from: 'a1',
          to: 'c1',
          flags: 'n',
          piece: 'r',
          san: 'Rc1',
        },
        {
          color: 'b',
          fen: 'rnb2rk1/p1p1qpp1/1p5p/3p4/3P4/4PN2/PP3PPP/2RQKB1R b K - 1 11',
          from: 'c8',
          to: 'e6',
          flags: 'n',
          piece: 'b',
          san: 'Be6',
        },
        {
          color: 'w',
          fen: 'rn3rk1/p1p1qpp1/1p2b2p/3p4/3P4/4PN2/PP3PPP/2RQKB1R w K - 2 12',
          from: 'd1',
          to: 'a4',
          flags: 'n',
          piece: 'q',
          san: 'Qa4',
        },
        {
          color: 'b',
          fen: 'rn3rk1/p1p1qpp1/1p2b2p/3p4/Q2P4/4PN2/PP3PPP/2R1KB1R b K - 3 12',
          from: 'c7',
          to: 'c5',
          flags: 'b',
          piece: 'p',
          san: 'c5',
        },
        {
          color: 'w',
          fen: 'rn3rk1/p3qpp1/1p2b2p/2pp4/Q2P4/4PN2/PP3PPP/2R1KB1R w K c6 0 13',
          from: 'a4',
          to: 'a3',
          flags: 'n',
          piece: 'q',
          san: 'Qa3',
        },
        {
          color: 'b',
          fen: 'rn3rk1/p3qpp1/1p2b2p/2pp4/3P4/Q3PN2/PP3PPP/2R1KB1R b K - 1 13',
          from: 'f8',
          to: 'c8',
          flags: 'n',
          piece: 'r',
          san: 'Rc8',
        },
        {
          color: 'w',
          fen: 'rnr3k1/p3qpp1/1p2b2p/2pp4/3P4/Q3PN2/PP3PPP/2R1KB1R w K - 2 14',
          from: 'f1',
          to: 'b5',
          flags: 'n',
          piece: 'b',
          san: 'Bb5',
        },
        {
          color: 'b',
          fen: 'rnr3k1/p3qpp1/1p2b2p/1Bpp4/3P4/Q3PN2/PP3PPP/2R1K2R b K - 3 14',
          from: 'a7',
          to: 'a6',
          flags: 'n',
          piece: 'p',
          san: 'a6',
        },
        {
          color: 'w',
          fen: 'rnr3k1/4qpp1/pp2b2p/1Bpp4/3P4/Q3PN2/PP3PPP/2R1K2R w K - 0 15',
          from: 'd4',
          to: 'c5',
          flags: 'c',
          piece: 'p',
          san: 'dxc5',
          captured: 'p',
        },
        {
          color: 'b',
          fen: 'rnr3k1/4qpp1/pp2b2p/1BPp4/8/Q3PN2/PP3PPP/2R1K2R b K - 0 15',
          from: 'b6',
          to: 'c5',
          flags: 'c',
          piece: 'p',
          san: 'bxc5',
          captured: 'p',
        },
        {
          color: 'w',
          fen: 'rnr3k1/4qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R1K2R w K - 0 16',
          from: 'e1',
          to: 'g1',
          flags: 'k',
          piece: 'k',
          san: 'O-O',
        },
        {
          color: 'b',
          fen: 'rnr3k1/4qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R2RK1 b - - 1 16',
          from: 'a8',
          to: 'a7',
          flags: 'n',
          piece: 'r',
          san: 'Ra7',
        },
        {
          color: 'w',
          fen: '1nr3k1/r3qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R2RK1 w - - 2 17',
          from: 'b5',
          to: 'e2',
          flags: 'n',
          piece: 'b',
          san: 'Be2',
        },
        {
          color: 'b',
          fen: '1nr3k1/r3qpp1/p3b2p/2pp4/8/Q3PN2/PP2BPPP/2R2RK1 b - - 3 17',
          from: 'b8',
          to: 'd7',
          flags: 'n',
          piece: 'n',
          san: 'Nd7',
        },
        {
          color: 'w',
          fen: '2r3k1/r2nqpp1/p3b2p/2pp4/8/Q3PN2/PP2BPPP/2R2RK1 w - - 4 18',
          from: 'f3',
          to: 'd4',
          flags: 'n',
          piece: 'n',
          san: 'Nd4',
        },
        {
          color: 'b',
          fen: '2r3k1/r2nqpp1/p3b2p/2pp4/3N4/Q3P3/PP2BPPP/2R2RK1 b - - 5 18',
          from: 'e7',
          to: 'f8',
          flags: 'n',
          piece: 'q',
          san: 'Qf8',
        },
        {
          color: 'w',
          fen: '2r2qk1/r2n1pp1/p3b2p/2pp4/3N4/Q3P3/PP2BPPP/2R2RK1 w - - 6 19',
          from: 'd4',
          to: 'e6',
          flags: 'c',
          piece: 'n',
          san: 'Nxe6',
          captured: 'b',
        },
        {
          color: 'b',
          fen: '2r2qk1/r2n1pp1/p3N2p/2pp4/8/Q3P3/PP2BPPP/2R2RK1 b - - 0 19',
          from: 'f7',
          to: 'e6',
          flags: 'c',
          piece: 'p',
          san: 'fxe6',
          captured: 'n',
        },
        {
          color: 'w',
          fen: '2r2qk1/r2n2p1/p3p2p/2pp4/8/Q3P3/PP2BPPP/2R2RK1 w - - 0 20',
          from: 'e3',
          to: 'e4',
          flags: 'n',
          piece: 'p',
          san: 'e4',
        },
        {
          color: 'b',
          fen: '2r2qk1/r2n2p1/p3p2p/2pp4/4P3/Q7/PP2BPPP/2R2RK1 b - - 0 20',
          from: 'd5',
          to: 'd4',
          flags: 'n',
          piece: 'p',
          san: 'd4',
        },
        {
          color: 'w',
          fen: '2r2qk1/r2n2p1/p3p2p/2p5/3pP3/Q7/PP2BPPP/2R2RK1 w - - 0 21',
          from: 'f2',
          to: 'f4',
          flags: 'b',
          piece: 'p',
          san: 'f4',
        },
        {
          color: 'b',
          fen: '2r2qk1/r2n2p1/p3p2p/2p5/3pPP2/Q7/PP2B1PP/2R2RK1 b - f3 0 21',
          from: 'f8',
          to: 'e7',
          flags: 'n',
          piece: 'q',
          san: 'Qe7',
        },
        {
          color: 'w',
          fen: '2r3k1/r2nq1p1/p3p2p/2p5/3pPP2/Q7/PP2B1PP/2R2RK1 w - - 1 22',
          from: 'e4',
          to: 'e5',
          flags: 'n',
          piece: 'p',
          san: 'e5',
        },
        {
          color: 'b',
          fen: '2r3k1/r2nq1p1/p3p2p/2p1P3/3p1P2/Q7/PP2B1PP/2R2RK1 b - - 0 22',
          from: 'c8',
          to: 'b8',
          flags: 'n',
          piece: 'r',
          san: 'Rb8',
        },
        {
          color: 'w',
          fen: '1r4k1/r2nq1p1/p3p2p/2p1P3/3p1P2/Q7/PP2B1PP/2R2RK1 w - - 1 23',
          from: 'e2',
          to: 'c4',
          flags: 'n',
          piece: 'b',
          san: 'Bc4',
        },
        {
          color: 'b',
          fen: '1r4k1/r2nq1p1/p3p2p/2p1P3/2Bp1P2/Q7/PP4PP/2R2RK1 b - - 2 23',
          from: 'g8',
          to: 'h8',
          flags: 'n',
          piece: 'k',
          san: 'Kh8',
        },
        {
          color: 'w',
          fen: '1r5k/r2nq1p1/p3p2p/2p1P3/2Bp1P2/Q7/PP4PP/2R2RK1 w - - 3 24',
          from: 'a3',
          to: 'h3',
          flags: 'n',
          piece: 'q',
          san: 'Qh3',
        },
        {
          color: 'b',
          fen: '1r5k/r2nq1p1/p3p2p/2p1P3/2Bp1P2/7Q/PP4PP/2R2RK1 b - - 4 24',
          from: 'd7',
          to: 'f8',
          flags: 'n',
          piece: 'n',
          san: 'Nf8',
        },
        {
          color: 'w',
          fen: '1r3n1k/r3q1p1/p3p2p/2p1P3/2Bp1P2/7Q/PP4PP/2R2RK1 w - - 5 25',
          from: 'b2',
          to: 'b3',
          flags: 'n',
          piece: 'p',
          san: 'b3',
        },
        {
          color: 'b',
          fen: '1r3n1k/r3q1p1/p3p2p/2p1P3/2Bp1P2/1P5Q/P5PP/2R2RK1 b - - 0 25',
          from: 'a6',
          to: 'a5',
          flags: 'n',
          piece: 'p',
          san: 'a5',
        },
        {
          color: 'w',
          fen: '1r3n1k/r3q1p1/4p2p/p1p1P3/2Bp1P2/1P5Q/P5PP/2R2RK1 w - - 0 26',
          from: 'f4',
          to: 'f5',
          flags: 'n',
          piece: 'p',
          san: 'f5',
        },
        {
          color: 'b',
          fen: '1r3n1k/r3q1p1/4p2p/p1p1PP2/2Bp4/1P5Q/P5PP/2R2RK1 b - - 0 26',
          from: 'e6',
          to: 'f5',
          flags: 'c',
          piece: 'p',
          san: 'exf5',
          captured: 'p',
        },
        {
          color: 'w',
          fen: '1r3n1k/r3q1p1/7p/p1p1Pp2/2Bp4/1P5Q/P5PP/2R2RK1 w - - 0 27',
          from: 'f1',
          to: 'f5',
          flags: 'c',
          piece: 'r',
          san: 'Rxf5',
          captured: 'p',
        },
        {
          color: 'b',
          fen: '1r3n1k/r3q1p1/7p/p1p1PR2/2Bp4/1P5Q/P5PP/2R3K1 b - - 0 27',
          from: 'f8',
          to: 'h7',
          flags: 'n',
          piece: 'n',
          san: 'Nh7',
        },
        {
          color: 'w',
          fen: '1r5k/r3q1pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/2R3K1 w - - 1 28',
          from: 'c1',
          to: 'f1',
          flags: 'n',
          piece: 'r',
          san: 'Rcf1',
        },
        {
          color: 'b',
          fen: '1r5k/r3q1pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/5RK1 b - - 2 28',
          from: 'e7',
          to: 'd8',
          flags: 'n',
          piece: 'q',
          san: 'Qd8',
        },
        {
          color: 'w',
          fen: '1r1q3k/r5pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/5RK1 w - - 3 29',
          from: 'h3',
          to: 'g3',
          flags: 'n',
          piece: 'q',
          san: 'Qg3',
        },
        {
          color: 'b',
          fen: '1r1q3k/r5pn/7p/p1p1PR2/2Bp4/1P4Q1/P5PP/5RK1 b - - 4 29',
          from: 'a7',
          to: 'e7',
          flags: 'n',
          piece: 'r',
          san: 'Re7',
        },
        {
          color: 'w',
          fen: '1r1q3k/4r1pn/7p/p1p1PR2/2Bp4/1P4Q1/P5PP/5RK1 w - - 5 30',
          from: 'h2',
          to: 'h4',
          flags: 'b',
          piece: 'p',
          san: 'h4',
        },
        {
          color: 'b',
          fen: '1r1q3k/4r1pn/7p/p1p1PR2/2Bp3P/1P4Q1/P5P1/5RK1 b - h3 0 30',
          from: 'b8',
          to: 'b7',
          flags: 'n',
          piece: 'r',
          san: 'Rbb7',
        },
        {
          color: 'w',
          fen: '3q3k/1r2r1pn/7p/p1p1PR2/2Bp3P/1P4Q1/P5P1/5RK1 w - - 1 31',
          from: 'e5',
          to: 'e6',
          flags: 'n',
          piece: 'p',
          san: 'e6',
        },
        {
          color: 'b',
          fen: '3q3k/1r2r1pn/4P2p/p1p2R2/2Bp3P/1P4Q1/P5P1/5RK1 b - - 0 31',
          from: 'b7',
          to: 'c7',
          flags: 'n',
          piece: 'r',
          san: 'Rbc7',
        },
        {
          color: 'w',
          fen: '3q3k/2r1r1pn/4P2p/p1p2R2/2Bp3P/1P4Q1/P5P1/5RK1 w - - 1 32',
          from: 'g3',
          to: 'e5',
          flags: 'n',
          piece: 'q',
          san: 'Qe5',
        },
        {
          color: 'b',
          fen: '3q3k/2r1r1pn/4P2p/p1p1QR2/2Bp3P/1P6/P5P1/5RK1 b - - 2 32',
          from: 'd8',
          to: 'e8',
          flags: 'n',
          piece: 'q',
          san: 'Qe8',
        },
        {
          color: 'w',
          fen: '4q2k/2r1r1pn/4P2p/p1p1QR2/2Bp3P/1P6/P5P1/5RK1 w - - 3 33',
          from: 'a2',
          to: 'a4',
          flags: 'b',
          piece: 'p',
          san: 'a4',
        },
        {
          color: 'b',
          fen: '4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/6P1/5RK1 b - a3 0 33',
          from: 'e8',
          to: 'd8',
          flags: 'n',
          piece: 'q',
          san: 'Qd8',
        },
        {
          color: 'w',
          fen: '3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/6P1/5RK1 w - - 1 34',
          from: 'f1',
          to: 'f2',
          flags: 'n',
          piece: 'r',
          san: 'R1f2',
        },
        {
          color: 'b',
          fen: '3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/5RP1/6K1 b - - 2 34',
          from: 'd8',
          to: 'e8',
          flags: 'n',
          piece: 'q',
          san: 'Qe8',
        },
        {
          color: 'w',
          fen: '4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/5RP1/6K1 w - - 3 35',
          from: 'f2',
          to: 'f3',
          flags: 'n',
          piece: 'r',
          san: 'R2f3',
        },
        {
          color: 'b',
          fen: '4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P3R2/6P1/6K1 b - - 4 35',
          from: 'e8',
          to: 'd8',
          flags: 'n',
          piece: 'q',
          san: 'Qd8',
        },
        {
          color: 'w',
          fen: '3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P3R2/6P1/6K1 w - - 5 36',
          from: 'c4',
          to: 'd3',
          flags: 'n',
          piece: 'b',
          san: 'Bd3',
        },
        {
          color: 'b',
          fen: '3q3k/2r1r1pn/4P2p/p1p1QR2/P2p3P/1P1B1R2/6P1/6K1 b - - 6 36',
          from: 'd8',
          to: 'e8',
          flags: 'n',
          piece: 'q',
          san: 'Qe8',
        },
        {
          color: 'w',
          fen: '4q2k/2r1r1pn/4P2p/p1p1QR2/P2p3P/1P1B1R2/6P1/6K1 w - - 7 37',
          from: 'e5',
          to: 'e4',
          flags: 'n',
          piece: 'q',
          san: 'Qe4',
        },
        {
          color: 'b',
          fen: '4q2k/2r1r1pn/4P2p/p1p2R2/P2pQ2P/1P1B1R2/6P1/6K1 b - - 8 37',
          from: 'h7',
          to: 'f6',
          flags: 'n',
          piece: 'n',
          san: 'Nf6',
        },
        {
          color: 'w',
          fen: '4q2k/2r1r1p1/4Pn1p/p1p2R2/P2pQ2P/1P1B1R2/6P1/6K1 w - - 9 38',
          from: 'f5',
          to: 'f6',
          flags: 'c',
          piece: 'r',
          san: 'Rxf6',
          captured: 'n',
        },
        {
          color: 'b',
          fen: '4q2k/2r1r1p1/4PR1p/p1p5/P2pQ2P/1P1B1R2/6P1/6K1 b - - 0 38',
          from: 'g7',
          to: 'f6',
          flags: 'c',
          piece: 'p',
          san: 'gxf6',
          captured: 'r',
        },
        {
          color: 'w',
          fen: '4q2k/2r1r3/4Pp1p/p1p5/P2pQ2P/1P1B1R2/6P1/6K1 w - - 0 39',
          from: 'f3',
          to: 'f6',
          flags: 'c',
          piece: 'r',
          san: 'Rxf6',
          captured: 'p',
        },
        {
          color: 'b',
          fen: '4q2k/2r1r3/4PR1p/p1p5/P2pQ2P/1P1B4/6P1/6K1 b - - 0 39',
          from: 'h8',
          to: 'g8',
          flags: 'n',
          piece: 'k',
          san: 'Kg8',
        },
        {
          color: 'w',
          fen: '4q1k1/2r1r3/4PR1p/p1p5/P2pQ2P/1P1B4/6P1/6K1 w - - 1 40',
          from: 'd3',
          to: 'c4',
          flags: 'n',
          piece: 'b',
          san: 'Bc4',
        },
        {
          color: 'b',
          fen: '4q1k1/2r1r3/4PR1p/p1p5/P1BpQ2P/1P6/6P1/6K1 b - - 2 40',
          from: 'g8',
          to: 'h8',
          flags: 'n',
          piece: 'k',
          san: 'Kh8',
        },
        {
          color: 'w',
          fen: '4q2k/2r1r3/4PR1p/p1p5/P1BpQ2P/1P6/6P1/6K1 w - - 3 41',
          from: 'e4',
          to: 'f4',
          flags: 'n',
          piece: 'q',
          san: 'Qf4',
        },
      ],
    },
  ]

  tests.forEach((t, i) => {
    it('History ' + i, () => {
      chess.reset()

      for (let j = 0; j < t.moves.length; j++) {
        chess.move(t.moves[j])
      }

      const history = chess.history({ verbose: t.verbose })
      expect(chess.fen()).toEqual(t.fen)
      expect(history.length).toEqual(t.moves.length)

      for (let j = 0; j < t.moves.length; j++) {
        expect(history[j]).toEqual(t.moves[j])
      }
    })
  })

  test('History - PGN Setup', () => {
    let pgn = `[SetUp "1"]
[FEN "r1bqk1nr/pppp1ppp/2n5/4p3/1bB1P3/2P2N2/P2P1PPP/RNBQK2R b KQkq - 0 1"]

1. ... Ba5 2. O-O d6
3. d4`

    const moves = [
      {
        fen: 'r1bqk1nr/pppp1ppp/2n5/4p3/1bB1P3/2P2N2/P2P1PPP/RNBQK2R b KQkq - 0 1',
        color: 'b',
        piece: 'b',
        from: 'b4',
        to: 'a5',
        san: 'Ba5',
        flags: 'n',
      },
      {
        fen: 'r1bqk1nr/pppp1ppp/2n5/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQK2R w KQkq - 1 2',
        color: 'w',
        piece: 'k',
        from: 'e1',
        to: 'g1',
        san: 'O-O',
        flags: 'k',
      },
      {
        fen: 'r1bqk1nr/pppp1ppp/2n5/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQ1RK1 b kq - 2 2',
        color: 'b',
        piece: 'p',
        from: 'd7',
        to: 'd6',
        san: 'd6',
        flags: 'n',
      },
      {
        fen: 'r1bqk1nr/ppp2ppp/2np4/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQ1RK1 w kq - 0 3',
        color: 'w',
        piece: 'p',
        from: 'd2',
        to: 'd4',
        san: 'd4',
        flags: 'b',
      },
    ]

    const chess = new Chess()
    chess.loadPgn(pgn)

    const history = chess.history({ verbose: true })

    moves.forEach((move, i) => {
      expect(history[i]).toEqual(move)
    })
  })
})
